var __transforms__video_8py =
[
    [ "torchvision_down.transforms._transforms_video.RandomCropVideo", "classtorchvision__down_1_1transforms_1_1__transforms__video_1_1_random_crop_video.html", "classtorchvision__down_1_1transforms_1_1__transforms__video_1_1_random_crop_video" ],
    [ "torchvision_down.transforms._transforms_video.RandomResizedCropVideo", "classtorchvision__down_1_1transforms_1_1__transforms__video_1_1_random_resized_crop_video.html", "classtorchvision__down_1_1transforms_1_1__transforms__video_1_1_random_resized_crop_video" ],
    [ "torchvision_down.transforms._transforms_video.CenterCropVideo", "classtorchvision__down_1_1transforms_1_1__transforms__video_1_1_center_crop_video.html", "classtorchvision__down_1_1transforms_1_1__transforms__video_1_1_center_crop_video" ],
    [ "torchvision_down.transforms._transforms_video.NormalizeVideo", "classtorchvision__down_1_1transforms_1_1__transforms__video_1_1_normalize_video.html", "classtorchvision__down_1_1transforms_1_1__transforms__video_1_1_normalize_video" ],
    [ "torchvision_down.transforms._transforms_video.ToTensorVideo", "classtorchvision__down_1_1transforms_1_1__transforms__video_1_1_to_tensor_video.html", "classtorchvision__down_1_1transforms_1_1__transforms__video_1_1_to_tensor_video" ],
    [ "torchvision_down.transforms._transforms_video.RandomHorizontalFlipVideo", "classtorchvision__down_1_1transforms_1_1__transforms__video_1_1_random_horizontal_flip_video.html", "classtorchvision__down_1_1transforms_1_1__transforms__video_1_1_random_horizontal_flip_video" ],
    [ "torchvision_down.transforms._transforms_video.__all__", "namespacetorchvision__down_1_1transforms_1_1__transforms__video.html#a361989188610ca01119f0f3dcd206733", null ]
];