var clip__sampler_8py =
[
    [ "torchvision_down.datasets.samplers.clip_sampler.DistributedSampler", "classtorchvision__down_1_1datasets_1_1samplers_1_1clip__sampler_1_1_distributed_sampler.html", "classtorchvision__down_1_1datasets_1_1samplers_1_1clip__sampler_1_1_distributed_sampler" ],
    [ "torchvision_down.datasets.samplers.clip_sampler.UniformClipSampler", "classtorchvision__down_1_1datasets_1_1samplers_1_1clip__sampler_1_1_uniform_clip_sampler.html", "classtorchvision__down_1_1datasets_1_1samplers_1_1clip__sampler_1_1_uniform_clip_sampler" ],
    [ "torchvision_down.datasets.samplers.clip_sampler.RandomClipSampler", "classtorchvision__down_1_1datasets_1_1samplers_1_1clip__sampler_1_1_random_clip_sampler.html", "classtorchvision__down_1_1datasets_1_1samplers_1_1clip__sampler_1_1_random_clip_sampler" ]
];