var namespacetorchvision__down_1_1models_1_1detection_1_1generalized__rcnn =
[
    [ "GeneralizedRCNN", "classtorchvision__down_1_1models_1_1detection_1_1generalized__rcnn_1_1_generalized_r_c_n_n.html", "classtorchvision__down_1_1models_1_1detection_1_1generalized__rcnn_1_1_generalized_r_c_n_n" ]
];