var quantization_2inception_8py =
[
    [ "torchvision_down.models.quantization.inception.QuantizableBasicConv2d", "classtorchvision__down_1_1models_1_1quantization_1_1inception_1_1_quantizable_basic_conv2d.html", "classtorchvision__down_1_1models_1_1quantization_1_1inception_1_1_quantizable_basic_conv2d" ],
    [ "torchvision_down.models.quantization.inception.QuantizableInceptionA", "classtorchvision__down_1_1models_1_1quantization_1_1inception_1_1_quantizable_inception_a.html", "classtorchvision__down_1_1models_1_1quantization_1_1inception_1_1_quantizable_inception_a" ],
    [ "torchvision_down.models.quantization.inception.QuantizableInceptionB", "classtorchvision__down_1_1models_1_1quantization_1_1inception_1_1_quantizable_inception_b.html", "classtorchvision__down_1_1models_1_1quantization_1_1inception_1_1_quantizable_inception_b" ],
    [ "torchvision_down.models.quantization.inception.QuantizableInceptionC", "classtorchvision__down_1_1models_1_1quantization_1_1inception_1_1_quantizable_inception_c.html", "classtorchvision__down_1_1models_1_1quantization_1_1inception_1_1_quantizable_inception_c" ],
    [ "torchvision_down.models.quantization.inception.QuantizableInceptionD", "classtorchvision__down_1_1models_1_1quantization_1_1inception_1_1_quantizable_inception_d.html", "classtorchvision__down_1_1models_1_1quantization_1_1inception_1_1_quantizable_inception_d" ],
    [ "torchvision_down.models.quantization.inception.QuantizableInceptionE", "classtorchvision__down_1_1models_1_1quantization_1_1inception_1_1_quantizable_inception_e.html", "classtorchvision__down_1_1models_1_1quantization_1_1inception_1_1_quantizable_inception_e" ],
    [ "torchvision_down.models.quantization.inception.QuantizableInceptionAux", "classtorchvision__down_1_1models_1_1quantization_1_1inception_1_1_quantizable_inception_aux.html", "classtorchvision__down_1_1models_1_1quantization_1_1inception_1_1_quantizable_inception_aux" ],
    [ "torchvision_down.models.quantization.inception.QuantizableInception3", "classtorchvision__down_1_1models_1_1quantization_1_1inception_1_1_quantizable_inception3.html", "classtorchvision__down_1_1models_1_1quantization_1_1inception_1_1_quantizable_inception3" ],
    [ "torchvision_down.models.quantization.inception.inception_v3", "namespacetorchvision__down_1_1models_1_1quantization_1_1inception.html#aa872f791870f69c9671ba7a25fbca7b8", null ],
    [ "torchvision_down.models.quantization.inception.__all__", "namespacetorchvision__down_1_1models_1_1quantization_1_1inception.html#a95a71d5139a69c9ea0a8e57aafb42f88", null ],
    [ "torchvision_down.models.quantization.inception.quant_model_urls", "namespacetorchvision__down_1_1models_1_1quantization_1_1inception.html#a6a92326c7da5160058404f9ba6f2784d", null ]
];